apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketchat-mongo
spec:
  serviceName: rocketchat-mongo
  replicas: 3
  selector:
    matchLabels:
      app: rocketchat-mongo
  template:
    metadata:
      labels:
        app: rocketchat-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: rocketmongo
          image: mongo:5.0
          command:
          - mongod
          - "--bind_ip_all"
          - "--replSet"
          - rs0
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
